"""Tests for the anatomical-derivatives path-builders in
``laion_fmri._paths``.

The dataset ships per-subject T1w/T2w volumes and a dedicated
brain mask under ``derivatives/anatomical/sub-XX/ses-PrismaAnat/
anat/``, generated by the ``dense-retinotopy-struct`` pipeline.
Each modality is published at two resolutions: full-res and
``res-1pt8`` (matching the functional grid).
"""

from laion_fmri._paths import (
    ANATOMICAL_SESSION,
    anatomical_file_path,
    anatomical_session_dir,
    anatomical_subject_dir,
)


def test_anatomical_subject_dir_resolves(synthetic_data_dir):
    """``derivatives/anatomical/sub-XX/`` resolves through the builder."""
    anat_dir = anatomical_subject_dir(synthetic_data_dir, "sub-01")
    assert anat_dir.is_dir()
    assert anat_dir.name == "sub-01"
    assert anat_dir.parent.name == "anatomical"


def test_anatomical_session_dir_uses_fixed_session(synthetic_data_dir):
    """The anatomical session is always ``ses-PrismaAnat``."""
    sess_dir = anatomical_session_dir(synthetic_data_dir, "sub-01")
    assert sess_dir.is_dir()
    assert sess_dir.name == "anat"
    assert sess_dir.parent.name == ANATOMICAL_SESSION


def test_anatomical_session_constant():
    """The session constant matches the bucket layout."""
    assert ANATOMICAL_SESSION == "ses-PrismaAnat"


def test_anatomical_t1w_full_res(synthetic_data_dir):
    """T1w at full resolution -> ``..._space-T1w_T1w.nii.gz``."""
    path = anatomical_file_path(
        synthetic_data_dir, "sub-01", suffix="T1w",
    )
    assert path.is_file()
    assert path.name == (
        "sub-01_ses-PrismaAnat_space-T1w_T1w.nii.gz"
    )


def test_anatomical_t1w_res_1pt8(synthetic_data_dir):
    """T1w at ``res-1pt8`` ends with the matching token."""
    path = anatomical_file_path(
        synthetic_data_dir, "sub-01", suffix="T1w", res="1pt8",
    )
    assert path.is_file()
    assert path.name == (
        "sub-01_ses-PrismaAnat_space-T1w_res-1pt8_T1w.nii.gz"
    )


def test_anatomical_t2w_full_res(synthetic_data_dir):
    """T2w volume resolves at full resolution."""
    path = anatomical_file_path(
        synthetic_data_dir, "sub-01", suffix="T2w",
    )
    assert path.is_file()
    assert path.name.endswith("_space-T1w_T2w.nii.gz")


def test_anatomical_brain_mask_full_res(synthetic_data_dir):
    """Brain mask at full resolution uses ``desc-brain``."""
    path = anatomical_file_path(
        synthetic_data_dir, "sub-01",
        suffix="mask", desc="brain",
    )
    assert path.is_file()
    assert path.name == (
        "sub-01_ses-PrismaAnat_space-T1w_desc-brain_mask.nii.gz"
    )


def test_anatomical_brain_mask_res_1pt8(synthetic_data_dir):
    """Brain mask at ``res-1pt8`` is what aligns with the functional grid."""
    path = anatomical_file_path(
        synthetic_data_dir, "sub-01",
        suffix="mask", desc="brain", res="1pt8",
    )
    assert path.is_file()
    assert path.name == (
        "sub-01_ses-PrismaAnat_space-T1w"
        "_res-1pt8_desc-brain_mask.nii.gz"
    )


def test_anatomical_file_path_rejects_unknown_suffix(synthetic_data_dir):
    """Unknown ``suffix`` raises ``ValueError``."""
    import pytest
    with pytest.raises(ValueError, match="suffix"):
        anatomical_file_path(
            synthetic_data_dir, "sub-01", suffix="DWI",
        )
